# Generated by Django 4.0.6 on 2022-08-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0002_alter_game_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='gamerraterapi.game'),
        ),
    ]
